[project]
name = "data-platform-core-cli"
version = "0.1.0"
description = "Core CLI"
readme = "../../../README.md"
requires-python = ">=3.12"
dependencies = [
    "click>=8.1.8",
    "data-platform-core-di",
    "dependency-injector>=4.45.0",
    "networkx>=3.4.2",
]

[tool.uv]
package = true

[tool.uv.sources]
data-platform-core-di = { workspace = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
sources = ["src"]
only-include = ["src/data_platform/core/cli"]


[project.scripts]
data-platform = "data_platform.core.cli:app"
