[hub]
server ansible_host=192.168.56.10 ansible_ssh_private_key_file=.vagrant/machines/server/libvirt/private_key

[spokes]
client1 ansible_host=192.168.56.11 ansible_ssh_private_key_file=.vagrant/machines/client1/libvirt/private_key
client2 ansible_host=192.168.56.12 ansible_ssh_private_key_file=.vagrant/machines/client2/libvirt/private_key

# Not part of the WireGuard mesh at all -- represents some other node that
# happens to share client1's non-WireGuard "foreign_lan" network.
[foreign_lan]
foreign ansible_host=192.168.60.20 ansible_ssh_private_key_file=.vagrant/machines/foreign/libvirt/private_key

[all:vars]
ansible_user=vagrant
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
