"""Facts specific to this study, not covered by pyinfra's built-ins."""
from typing import NamedTuple

from pyinfra.api import FactBase


class WireguardKeypair(NamedTuple):
    private: str
    public: str


class WireguardKey(FactBase):
    """This host's own wg0 keypair -- generating it on first use.

    Deliberately NOT a pure, read-only fact, unlike pyinfra convention:
    pyinfra runs every fact during the "prepare" phase, strictly before
    any operation executes (even ones added earlier in this same deploy
    script) -- see deploy.py's own note on this. Something generated by
    an *operation* (wireguard-tools itself, the keypair) would therefore
    never exist yet by the time a later fact tried to read it, on a
    fresh host. Folding "install wireguard-tools and generate the key if
    missing" and "read it back" into one atomic remote command sidesteps
    that ordering problem entirely -- correctness here only depends on
    the command being idempotent (safe to re-run), which it is: the key
    is generated once, ever, and -- same as the old Ansible playbook --
    it never leaves the host it was generated on. deploy.py reads a
    *peer's* pubkey the same way, via inventory.get_host(peer).get_fact
    (WireguardKey), which opens its own independent SSH connection to
    that peer right then and there, so it bootstraps correctly no matter
    which host's turn in the prepare phase happens to run first.
    """

    def command(self):
        return (
            "pacman -S --needed --noconfirm wireguard-tools >/dev/null 2>&1; "
            "umask 077 && test -f /etc/wireguard/wg0.key || wg genkey > /etc/wireguard/wg0.key; "
            "cat /etc/wireguard/wg0.key; "
            "wg pubkey < /etc/wireguard/wg0.key"
        )

    def process(self, output):
        private, public = output
        return WireguardKeypair(private=private, public=public)


class InterfaceWithAddress(FactBase):
    """The name of the interface currently holding the given IPv4 address.

    Vagrant/libvirt don't let us pick the guest's interface name for the
    foreign_lan NIC in advance, so find whichever interface actually got
    it at boot.
    """

    def command(self, ip):
        return "ip -4 -o addr show | awk '$4 ~ \"^{}/\" {{print $2; exit}}'".format(ip)

    def process(self, output):
        return output[0] if output else None


class NsswitchHostsLine(FactBase):
    """The current (uncommented) `hosts:` line from /etc/nsswitch.conf."""

    command = "grep '^hosts:' /etc/nsswitch.conf"
