[project]
name = "data-platform-core-di"
version = "0.1.0"
description = "Core DI"
readme = "../../../README.md"
requires-python = ">=3.13"
dependencies = []

[tool.uv]
package = true

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
sources = ["src"]
only-include = ["src/data_platform/core/di"]