[project]
name = "try-gemini"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "colorama>=0.4.6",
    "google-genai>=1.23.0",
    "pydantic>=2.11.7",
]
