#!/usr/bin/env python3

from http.server import BaseHTTPRequestHandler, HTTPServer
import logging
from subprocess import run

HELLO = "<h1>Hello! </h1>"

class HTTPRequestHandler(BaseHTTPRequestHandler):

    def _set_response(self):
        self.send_response(200)
        self.send_header('Content-type', 'text/html')
        self.end_headers()

    def do_GET(self):
        self._set_response()
        self.wfile.write(HELLO.encode("utf-8"))

def serve(server_class=HTTPServer, handler_class=HTTPRequestHandler, port=8080):
    logging.basicConfig(level=logging.INFO)
    server_address = ('127.0.0.1', port)
    server = server_class(server_address, handler_class)
    logging.info('Starting httpd...\n')

    #run(["systemd-notify", "READY=1"])
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        pass
    server.server_close()
    logging.info('Stopping httpd...\n')

if __name__ == '__main__':
    from sys import argv

    if len(argv) == 2:
        serve(port=int(argv[1]))
    else:
        serve()