[project]
name = "data-platform-tools-dbt"
version = "0.1.0"
description = "DBT Tool"
readme = "../../../README.md"
requires-python = ">=3.13"
dependencies = [
    "dependency-injector>=4.45.0",
]

[tool.uv]
package = true

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
sources = ["src"]
only-include = ["src/data_platform/tools/dbt"]

[project.entry-points."data_platform.core.di.modules"]
dbt = "data_platform.tools.dbt:Module"